# Indicates compatibility version with lifecycle
api = "0.2"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
  id = "nncdevel-io/paketo-newrelic-java-agent"
  name = "New Relic Java Agent APM"
  version = "0.0.1"

# The list of stacks that the buildpack itself is compatible with
[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BP_NEWRELIC_AGENT_VERSION"
description = "the New Relic-java-agent version"
default     = "7.6.0"
build       = true

[[metadata.dependencies]]
  id      = "newrelic-java-agent"
  name    = "newrelic-java-agent"
  version = "7.6.0"
  uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/7.6.0/newrelic-agent-7.6.0.jar"
  stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]
