FROM centos:latest AS pack

ARG PACK_VERSION=v0.13.1
ARG http_proxy
ARG https_proxy

RUN curl -L -o pack-${PACK_VERSION}-linux.tgz https://github.com/buildpacks/pack/releases/download/${PACK_VERSION}/pack-${PACK_VERSION}-linux.tgz
RUN tar xvf pack-${PACK_VERSION}-linux.tgz && \
    rm pack-${PACK_VERSION}-linux.tgz && \
    mv pack /bin/pack && \
    pack --help

